### PR TITLE
feat: Add "Jump to content" translations

### PR DESCRIPTION
**Pull request by skspade**
Create translations for "Jump to conent"

### CODE REVIEW

**Comment by skspade** [comment]
Not sure what more I need to do to make woodpecker happy here. I ran `prettier -c  .` and got the same response as woodpecker. 
Ran `prettier --write "**/*.json"`
Committed all changes.
Pushed. 
Woodpecker still fails. 

However I ran `prettier -c .` again and locally found no errors. 

```bash
➜  lemmy-translations git:(1117-jump--to-content) prettier --write "**/*.json"
email/bg.json 21ms
email/da.json 2ms
email/de.json 2ms
email/el.json 2ms
email/en.json 2ms
email/eo.json 2ms
email/es.json 1ms
email/eu.json 1ms
email/fi.json 2ms
email/fr.json 2ms
email/hu.json 1ms
email/id.json 2ms
email/it.json 1ms
email/ja.json 1ms
email/ko.json 1ms
email/oc.json 2ms
email/pl.json 2ms
email/pt_BR.json 1ms
email/pt.json 2ms
email/ro.json 1ms
email/ru.json 1ms
email/sk.json 0ms
email/tr.json 0ms
email/uk.json 1ms
email/zh_Hant.json 1ms
translations/ar.json 16ms
translations/as.json 3ms
translations/bg.json 7ms
translations/bn.json 2ms
translations/ca.json 3ms
translations/cs.json 6ms
translations/cy.json 1ms
translations/da.json 6ms
translations/de.json 5ms
translations/el.json 7ms
translations/en.json 4ms
translations/eo.json 7ms
translations/es.json 5ms
translations/eu.json 4ms
translations/fa.json 3ms
translations/fi.json 6ms
translations/fr.json 5ms
translations/ga.json 3ms
translations/gl.json 6ms
translations/got.json 1ms
translations/hi.json 2ms
translations/hr.json 1ms
translations/hu.json 9ms
translations/id.json 4ms
translations/it.json 5ms
translations/ja.json 7ms
translations/ka.json 2ms
translations/km.json 0ms
translations/ko.json 4ms
translations/lt.json 3ms
translations/ml.json 2ms
translations/mnc.json 0ms
translations/nb_NO.json 1ms
translations/nl.json 3ms
translations/oc.json 3ms
translations/pl.json 5ms
translations/pt_BR.json 4ms
translations/pt.json 4ms
translations/ro.json 0ms
translations/ru.json 5ms
translations/sk.json 5ms
translations/sq.json 2ms
translations/sr_Latn.json 1ms
translations/sv.json 3ms
translations/th.json 1ms
translations/tr.json 2ms
translations/uk.json 3ms
translations/vi.json 4ms
translations/zh_Hant.json 4ms
translations/zh.json 4ms
translators.json 3ms
➜  lemmy-translations git:(1117-jump--to-content) prettier -c .               
Checking formatting...
All matched files use Prettier code style!
➜  lemmy-translations git:(1117-jump--to-content) 
```

**Comment by SleeplessOne1917** [comment]
I think there might be a problem with the CI instead of on your end.

**Comment by skspade** [comment]
Makes sense! Maybe it's not pulling my latest commit instead is pulling from the commit that was present upon opening the PR?

**Comment by Nutomic** [comment]
It looks like we need to remvoe the formatting (see #51). For this change you should revert all changes and only add the single line in en.json.

**Comment by skspade** [comment]
Later today Ill hop on and remove all changes except the en.json translation and then force push to this PR. I'll ping you once I am done

**Comment by dessalines** [comment]
Sorry about that, the removal of the prettier check is merged.

**Comment by dessalines** [comment]
LGTM.

**Pull request merged**
